import pytest
import os
import subprocess
import configparser
import numpy as np
from netCDF4 import Dataset
import sys

# Import custom check functions and utilities
from check_data import check_dmat_files, check_elph_files
from convert_data import convert_save_dbs, generate_binary_ph_save
from test_list import tests

def make_inp_file(dict_list, qpools=1, kpools=1, filename="test_input.in"):
    with open(filename, "w") as f:
        f.write("## Input generated by LetzElPhC pytest suite.\n")
        f.write(f"nkpool = {int(kpools)} \n")
        f.write(f"nqpool = {int(qpools)} \n")
        for i in dict_list:
            key = i.lower().strip()
            if key == 'run_mode' or key.endswith('_ref'):
                continue
            f.write(f"{i.strip()} = {dict_list[i]} \n")

def find_factors(n):
    from functools import reduce
    return list(set(reduce(list.__add__, ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0))))

def get_triplet(n, nq_max, nk_max):
    n_factors = find_factors(n)
    triplet = []
    for ifac in n_factors:
        ifac_factors = find_factors(ifac)
        for jfac in ifac_factors:
            kfac = ifac // jfac
            if jfac <= nq_max and kfac <= nk_max:
                triplet.append([jfac, kfac])
    return triplet

def get_test_cases():
    cases = []
    base_dir = os.path.dirname(__file__)
    for folder, ini_file in tests:
        ini_path = os.path.join(base_dir, folder, ini_file)
        if not os.path.exists(ini_path):
            continue
        
        config = configparser.ConfigParser()
        config.read(ini_path)
        
        for section in config.sections():
            if section.strip() == 'DEFAULT':
                continue
            
            # Split section name e.g. "test1 qe"
            split_key = section.strip().split(' ')
            code = 'qe'
            if len(split_key) > 1:
                code = split_key[-1].strip()
                
            cases.append((folder, section, code, dict(config['DEFAULT']), dict(config[section])))
            
    return cases

@pytest.mark.parametrize("folder,section,code,default_cfg,test_cfg", get_test_cases())
def test_lelphc_integration(folder, section, code, default_cfg, test_cfg, pytestconfig, capfd):
    lelphc_cmd = pytestconfig.getoption("--lelphc")
    if lelphc_cmd.startswith(".") or "/" in lelphc_cmd:
        lelphc_cmd = os.path.abspath(lelphc_cmd)
        
    mpirun_cmd = pytestconfig.getoption("--mpirun")
    ncpus = pytestconfig.getoption("--ncpus")
    
    # Merge configs
    cfg = {**default_cfg, **test_cfg}
    run_mode = cfg.get("run_mode", "standard").lower()
    
    elph_db_ref = cfg.get('elph_db_ref', 'ndb.elph_ref')
    dmat_db_ref = cfg.get('dmat_db_ref', 'ndb.Dmats_ref')
    cwd = os.getcwd()
    base_dir = os.path.dirname(__file__)
    test_dir = os.path.join(base_dir, folder)
    os.chdir(test_dir)
    
    try:
        # Determine max pools
        try:
            with Dataset(elph_db_ref, 'r') as elph_ref_db:
                nkpool_max = elph_ref_db['kpoints'][...].data.shape[0]
                nqpool_max = elph_ref_db['qpoints_iBZ'][...].data.shape[0]
        except Exception as e:
            pytest.skip(f"Reference file issue: {e}")
            
        # Convert DBs
        try:
            ph_save = cfg.get('ph_save_dir', 'ph_save')
            generate_binary_ph_save(ph_save)
            save_dir = cfg.get('save_dir', 'SAVE')
            
            # Double vs Single detection
            ver_cmd = f"{mpirun_cmd} -n 1 {lelphc_cmd} --version"
            ver_res = subprocess.run(ver_cmd, shell=True, capture_output=True, text=True)
            dtype_out = np.double if "Double" in ver_res.stdout else np.single
            
            convert_save_dbs(save_dir, [np.double, np.single], dtype_out)
        except Exception as e:
            pytest.skip(f"Data conversion issue: {e}")

        # Execute tests for 1 CPU and ncpus
        cpu_sets = [1]
        if ncpus > 1:
            cpu_sets.append(ncpus)
            
        for icpu in cpu_sets:
            processor_sets = get_triplet(icpu, nqpool_max, nkpool_max)
            for jfac, kfac in processor_sets:
                make_inp_file(cfg, jfac, kfac, "test_input.in")
                
                # Setup flags based on run mode
                flags = f"-F test_input.in"
                if run_mode == "interpolation":
                    flags = f"-i -F test_input.in"
                
                run_cmd = f"{mpirun_cmd} -n {icpu} {lelphc_cmd} --code={code} {flags}"
                print(f"Running: {run_cmd}")
                
                res = subprocess.run(run_cmd, shell=True, capture_output=True, text=True)
                
                # Write to output file exactly as requested
                with open("TEST_RUN_OUTPUT", "a") as out_f:
                    out_f.write(f"\n--- RUN: {section} (CPUs: {icpu}) ---\n")
                    out_f.write(res.stdout)
                    out_f.write(res.stderr)
                    
                if res.returncode != 0:
                    pytest.fail(f"Lelphc execution failed. Check TEST_RUN_OUTPUT. Stderr: {res.stderr}")
                
                # Verification based on run_mode
                if run_mode == "standard":
                    assert check_dmat_files('ndb.Dmats', dmat_db_ref), "Dmats mismatch"
                    assert check_elph_files('ndb.elph', elph_db_ref), "elph DB mismatch"
                elif run_mode == "interpolation":
                    # Add your interpolation check functions here in the future
                    # e.g., assert check_interp_files('ndb.interp', ref_interp)
                    pass
                else:
                    pytest.fail(f"Unknown run_mode: {run_mode}")
                
                # Cleanup iteration
                os.system('rm -f test_input.in ndb.elph ndb.Dmats')

    finally:
        os.chdir(cwd)
